# Generated by Django 5.2.7 on 2025-10-05 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJSONFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên layer')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('file', models.FileField(upload_to='geojson_files/', verbose_name='File GeoJSON')),
                ('color', models.CharField(default='#FF0000', max_length=7, verbose_name='Màu sắc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GeoJSON File',
                'verbose_name_plural': 'GeoJSON Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('geojson_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.geojsonfile')),
            ],
            options={
                'verbose_name': 'Map Layer',
                'verbose_name_plural': 'Map Layers',
                'ordering': ['order'],
            },
        ),
    ]
