# Generated by Django 5.2.7 on 2025-10-05 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_index', models.IntegerField(verbose_name='Chỉ số feature')),
                ('feature_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên feature')),
                ('feature_address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ feature')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('map_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_visibilities', to='maps.maplayer')),
            ],
            options={
                'verbose_name': 'Feature Visibility',
                'verbose_name_plural': 'Feature Visibilities',
                'ordering': ['feature_index'],
                'unique_together': {('map_layer', 'feature_index')},
            },
        ),
    ]
