# Generated by Django 5.2.7 on 2025-10-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_featurevisibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonfile',
            name='symbol',
            field=models.CharField(default='marker', max_length=50, verbose_name='Map Symbol'),
        ),
        migrations.AlterField(
            model_name='featurevisibility',
            name='feature_address',
            field=models.TextField(blank=True, null=True, verbose_name='Feature Address'),
        ),
        migrations.AlterField(
            model_name='featurevisibility',
            name='feature_index',
            field=models.IntegerField(verbose_name='Feature Index'),
        ),
        migrations.AlterField(
            model_name='featurevisibility',
            name='feature_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Feature Name'),
        ),
        migrations.AlterField(
            model_name='featurevisibility',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='geojsonfile',
            name='color',
            field=models.CharField(default='#007cff', max_length=7, verbose_name='Display Color'),
        ),
        migrations.AlterField(
            model_name='geojsonfile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='geojsonfile',
            name='file',
            field=models.FileField(upload_to='geojson_files/', verbose_name='GeoJSON File'),
        ),
        migrations.AlterField(
            model_name='geojsonfile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='geojsonfile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Layer Name'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
