# Generated by Django 5.2.7 on 2025-10-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='geojsonfile',
            name='map_type',
            field=models.CharField(choices=[('embed', 'Embed Map'), ('embed_vn', 'Embed VN Map')], default='embed', max_length=20, verbose_name='Map Type'),
        ),
    ]
