# Generated by Django 5.2.7 on 2025-10-11 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_delete_location_geojsonfile_map_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Symbol Name')),
                ('image', models.ImageField(upload_to='symbols/', verbose_name='Symbol Image')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Symbol',
                'verbose_name_plural': 'Custom Symbols',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='geojsonfile',
            name='symbol',
            field=models.CharField(default='marker', max_length=50, verbose_name='Map Symbol (Legacy)'),
        ),
        migrations.AddField(
            model_name='geojsonfile',
            name='custom_symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.customsymbol', verbose_name='Custom Symbol'),
        ),
    ]
