# Generated by Django 5.2.7 on 2025-10-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_customsymbol_alter_geojsonfile_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojsonfile',
            name='edited_content',
            field=models.TextField(blank=True, null=True, verbose_name='Edited JSON Content'),
        ),
    ]
